import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        surface: "#0e1416",
        "surface-dim": "#0e1416",
        "surface-bright": "#343a3c",
        "surface-container-lowest": "#090f11",
        "surface-container-low": "#171d1e",
        "surface-container": "#1b2122",
        "surface-container-high": "#252b2d",
        "surface-container-highest": "#303638",
        "on-surface": "#dee3e6",
        "on-surface-variant": "#bcc9cd",
        "inverse-surface": "#dee3e6",
        "inverse-on-surface": "#2b3133",
        outline: "#869397",
        "outline-variant": "#3d494c",
        "surface-tint": "#4cd7f6",
        primary: "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        secondary: "#c0c1ff",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "on-secondary-container": "#b0b2ff",
        tertiary: "#ffb873",
        "on-tertiary": "#4b2800",
        "tertiary-container": "#e89337",
        "on-tertiary-container": "#5b3200",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5c",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
        background: "#0e1416",
        "on-background": "#dee3e6",
        "surface-variant": "#303638",
      },
    },
  },
};

export default config;
